import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import AdminDataTable from '../components/AdminDataTable';
import AdminStatCard from '../components/AdminStatCard';
import * as adminService from '../adminService';
import { Card } from '../../components/ui/Card';
import { Icon } from '../../components/ui/Icon';
import { Badge } from '../../components/ui/Badge';
import { PageHeader } from '../../components/ui/PageHeader';
import { Loading, ErrorState } from '../../components/ui/States';
import { apiError, formatDateTime } from '../../utils/format';

export default function AdminReports() {
  const navigate = useNavigate();
  const [rows, setRows] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = async () => {
    setLoading(true);
    setError('');
    try {
      setRows(await adminService.listReports());
    } catch (err) {
      setError(apiError(err, 'Could not load reports.'));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  if (loading) return <Loading variant="table" />;
  if (error) return <ErrorState message={error} onRetry={load} />;

  const list = rows || [];

  return (
    <div className="admin-page">
      <PageHeader eyebrow="Analytics" eyebrowIcon="report" title="Reports" subtitle="Reports generated by users across the platform." />
      <div className="stat-grid">
        <AdminStatCard label="Reports" value={list.length} icon="report" tone="primary" />
        <AdminStatCard label="Analyses covered" value={new Set(list.map((r) => r.analysis_id)).size} icon="chartLine" />
      </div>
      <Card flush>
        <AdminDataTable
          caption="Reports"
          columns={[
            { key: 'id', header: 'Report', render: (r) => <span className="row" style={{ gap: 8, flexWrap: 'nowrap' }}><Icon name="report" size={15} /> <span className="cell-strong">#{r.id}</span></span> },
            { key: 'analysis_id', header: 'Analysis', render: (r) => `#${r.analysis_id}` },
            { key: 'user_id', header: 'User', render: (r) => `#${r.user_id}` },
            { key: 'report_type', header: 'Type', render: (r) => <Badge tone="primary">{r.report_type}</Badge> },
            { key: 'created_at', header: 'Created', render: (r) => <span className="tabular">{formatDateTime(r.created_at)}</span> },
            {
              key: 'actions',
              header: '',
              sortable: false,
              render: (r) => (
                <button className="btn-ghost btn-sm" type="button" onClick={() => navigate(`/admin/analyses/${r.analysis_id}`)}>
                  Open analysis <Icon name="arrowRight" size={13} />
                </button>
              ),
            },
          ]}
          rows={list}
        />
      </Card>
    </div>
  );
}
